CREATE TABLE "P2112423"."MEDECIN" 
   (	"IDMEDECIN" NUMBER(8,0) NOT NULL ENABLE, 
	"NOMMEDECIN" VARCHAR2(40 BYTE), 
	"SPECIALITEMEDECIN" VARCHAR2(40 BYTE), 
	"ADRMEDECIN" VARCHAR2(80 BYTE), 
	 CONSTRAINT "MEDECIN_PK" PRIMARY KEY ("IDMEDECIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE" ;


  CREATE TABLE "P2112423"."MEDICAMENT" 
   (	"IDMEDICAMENT" NUMBER(8,0) NOT NULL ENABLE, 
	"DESIGNATIONMED" VARCHAR2(120 BYTE), 
	"EFFETMED" VARCHAR2(120 BYTE), 
	"POSOLOGIEMED" VARCHAR2(80 BYTE), 
	"PRIXLABORATOIRE" NUMBER(6,2) DEFAULT NULL, 
	 CONSTRAINT "MEDICAMENT_PK" PRIMARY KEY ("IDMEDICAMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE" ;


  CREATE TABLE "P2112423"."VENDEUR" 
   (	"IDVENDEUR" NUMBER(8,0) NOT NULL ENABLE, 
	"NOMVENDEUR" VARCHAR2(40 BYTE), 
	"ADRVENDEUR" VARCHAR2(80 BYTE), 
	"TELVENDEUR" VARCHAR2(10 BYTE), 
	 CONSTRAINT "VENDEUR_PK" PRIMARY KEY ("IDVENDEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE" ;



  CREATE TABLE "P2112423"."VENDS" 
   (	"IDVENDEUR" NUMBER(8,0) NOT NULL ENABLE, 
	"IDMEDICAMENT" NUMBER(8,0) NOT NULL ENABLE, 
	"PRIXVENTE" NUMBER(6,2), 
	 CONSTRAINT "VENDS_PK" PRIMARY KEY ("IDVENDEUR", "IDMEDICAMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE"  ENABLE, 
	 CONSTRAINT "VENDS_IDMEDICAMENT_FK" FOREIGN KEY ("IDMEDICAMENT")
	  REFERENCES "P2112423"."MEDICAMENT" ("IDMEDICAMENT") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "VENDS_IDVENDEUR_FK" FOREIGN KEY ("IDVENDEUR")
	  REFERENCES "P2112423"."VENDEUR" ("IDVENDEUR") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE" ;



  CREATE TABLE "P2112423"."PRESCRIRE" 
   (	"IDMEDECIN" NUMBER(8,0) NOT NULL ENABLE, 
	"IDMEDICAMENT" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "PRESCRIRE_PK" PRIMARY KEY ("IDMEDECIN", "IDMEDICAMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE"  ENABLE, 
	 CONSTRAINT "PRESCRIRE_IDMEDICAMENT_FK" FOREIGN KEY ("IDMEDICAMENT")
	  REFERENCES "P2112423"."MEDICAMENT" ("IDMEDICAMENT") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "PRESCRIRE_IDMEDECIN_FK" FOREIGN KEY ("IDMEDECIN")
	  REFERENCES "P2112423"."MEDECIN" ("IDMEDECIN") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LICENCE" ;


create or replace TRIGGER MEDECIN_TRG 
BEFORE INSERT ON MEDECIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDMEDECIN IS NULL THEN
      SELECT MEDECIN_SEQ.NEXTVAL INTO :NEW.IDMEDECIN FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



create or replace TRIGGER MEDICAMENT_TRG 
BEFORE INSERT ON MEDICAMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDMEDICAMENT IS NULL THEN
      SELECT MEDICAMENT_SEQ.NEXTVAL INTO :NEW.IDMEDICAMENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;




create or replace TRIGGER VENDEUR_TRG 
BEFORE INSERT ON VENDEUR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDVENDEUR IS NULL THEN
      SELECT VENDEUR_SEQ.NEXTVAL INTO :NEW.IDVENDEUR FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;